export const groupName = [
  "Jelly Belly Official Flavors",
  "Kids Mix Flavors",
  "Cold Stone® Flavors",
  "Sunkist® Citrus Mix Flavors",
  "Superfruit Flavors",
  "Sours Flavors",
  "Krispy Kreme® Doughnuts Flavors",
  "Soda Pop Shoppe® Flavors",
  "Sugar-Free Assorted Flavors",
  "Jewel Jelly Beans Flavors",
  "Snapple™ Mix Flavors",
  "Cocktail Classics® Flavors",
  "Tropical Mix Flavors",
  "Boba Milk Tea Flavors",
];

export const flavourName = [
  "7up",
  "a w cream soda",
  "a w root bear",
  "Acai Berry",
  "Apple Pie la Cold Stone",
  "Barbados Cherry",
  "Berry Blue",
  "Birthday Cake",
  "Birthday Cake Remix",
  "Blue Raspberry",
  "Blueberry",
  "Bubble Gum",
  "Buttered Popcorn",
  "Cantaloupe",
  "Cappuccino",
  "Caramel Corn",
  "Cherry Passion Fruit Smoothie",
  "Chocolate Devotion",
  "Chocolate Pudding",
  "Cinnamon",
  "Cinnamon Apple Filled",
  "Coconut",
  "Cotton Candy",
  "Cranberry",
  "Cranberry Raspberry",
  "Crushed Pineapple",
  "DrPepper",
  "French Vanilla",
  "Gin Tonic",
  "Glazed Blueberry Cake",
  "Grape Crush",
  "Green Apple",
  "Island Punch",
  "Jewel Berry Blue",
  "Jewel Blueberry",
  "Jewel BubbleGum",
  "Jewel Champagne",
  "Jewel CreamSoda",
  "Jewel GingerAle",
  "Jewel GrapeSoda",
  "Jewel Orange",
  "Jewel Sour Apple",
  "Jewel Sour Lemon",
  "Jewel Very Cherry",
  "Juicy Pear",
  "Kiwi",
  "Kiwi Strawberry",
  "Lemon",
  "Lemon Drop",
  "Lemon Lime",
  "Lemon meringue Pie",
  "Licorice",
  "Mandarin Orange Mango Smoothie",
  "Mango",
  "Mango Madness",
  "Mango Milke Tea",
  "Margarita",
  "Matcha Milk Tea",
  "Mimosa",
  "Mint Chocolate Chip",
  "Mixed Berry Smoothie",
  "Mojito",
  "Moscow Mule",
  "Orange Crush",
  "Orange Sherbet",
  "Original Glazed",
  "Our Strawberry Blonde",
  "Peach",
  "Pineapple Pear Smoothie",
  "Pink Lemonade",
  "Pina Colada",
  "Plum",
  "Pomegranate",
  "Pomegranate Cosmo",
  "Raspberry",
  "Red Apple",
  "Rose",
  "Smores",
  "Sizzling Cinnamon",
  "Sour Apple",
  "Sour Cherry",
  "Sour Grape",
  "Sour Lemon",
  "Sour Orange",
  "Strawberry Banana Smoothie",
  "Strawberry Cheesecake",
  "Strawberry Daiquiri",
  "Strawberry Iced",
  "Strawberry Jam",
  "Strawberry Milk Tea",
  "Sunkist Lemon",
  "Sunkist Lime",
  "Sunkist Orange",
  "Sunkist Pink Grapefruit",
  "Sunkist Tangerine",
  "Taro Milk Tea",
  "Thai Milk Tea",
  "Toasted Marshmallow",
  "Top Banana",
  "Tutti Fruitti",
  "Very Cherry",
  "Watermelon",
  "Wild Blackberry",
];

export const colourGroup = [
  { colour: "antiquewhite", description: "Creamy Off-White", hex: "#EEE7D8" },
  { colour: "black", description: "Pure Black", hex: "#000000" },
  {
    colour: "brown",
    description: "Rich Earthy Brown",
    hex: "#871922, #972C3F, #9E222C, #AD1E34",
  },
  {
    colour: "burlywood",
    description: "Warm Medium Tan",
    hex: "#EBC669, #F0C57F",
  },
  { colour: "coral", description: "Vibrant Pinkish-Orange", hex: "#EE734A" },
  { colour: "crimson", description: "Deep Vivid Red", hex: "#c4293e" },
  { colour: "darkgray", description: "Dark Steel Gray", hex: "#B598AF" },
  { colour: "darkgreen", description: "Deep Forest Green", hex: "#264D16" },
  {
    colour: "darkkhaki",
    description: "Olive Greenish-Brown",
    hex: "#D5DC55, #c8cf65",
  },
  { colour: "darksalmon", description: "Faded Pink-Orange", hex: "#E6986B" },
  {
    colour: "darkseagreen",
    description: "Muted Green with Gray Tint",
    hex: "#83AD5C",
  },
  {
    colour: "darkslategray",
    description: "Dark Grayish-Blue",
    hex: "#022F34, #293656, #402427, #553E5C, #5B3640",
  },
  {
    colour: "dimgray",
    description: "Medium-Dark Gray",
    hex: "#4F657C, #655277",
  },
  {
    colour: "firebrick",
    description: "Deep Brick Red",
    hex: "#B11F29, #C02032",
  },
  {
    colour: "forestgreen",
    description: "Classic Pine Green",
    hex: "#0E7534, #2B9B39, #3C812A",
  },
  {
    colour: "gainsboro",
    description: "Very Light Gray",
    hex: "#E1DFE1, #E5DCD5",
  },
  {
    colour: "gold",
    description: "Bright Metallic Gold",
    hex: "#F1C720, #F6D334, #F9D501, #FFE92D",
  },
  {
    colour: "goldenrod",
    description: "Earthy Yellow-Brown",
    hex: "#CCA42C, #D1CA3D, #D6BA03, #E5932E, #F99B25, #FAA538, #f99b24",
  },
  {
    colour: "indianred",
    description: "Dusty Red Earth",
    hex: "#9C4B6F, #B95A66, #DD4B62, #da566a",
  },
  {
    colour: "khaki",
    description: "Light Tan Brown",
    hex: "#C2E189, #CEDC91, #EFE393, #FADF50, #FDE96C",
  },
  {
    colour: "lightgray",
    description: "Pale Silver Gray",
    hex: "#CED8C2, #D2D0CE",
  },
  {
    colour: "lightpink",
    description: "Soft Baby Pink",
    hex: "#E3ACBD, #E798AB, #EFB3CB, #FF9BB3",
  },
  { colour: "lightsalmon", description: "Light Peachy Orange", hex: "#F79C72" },
  {
    colour: "peru",
    description: "Warm Earthy Orange-Brown",
    hex: "#AD7E47, #D48840, #EB8435, #ba815c, #c2864b",
  },
  { colour: "pink", description: "Soft Light Pink", hex: "#F9CAC8" },
  { colour: "rosybrown", description: "Muted Pink-Brown", hex: "#CD8784" },
  {
    colour: "saddlebrown",
    description: "Dark Brown with Red Tint",
    hex: "#5A262A, #602825, #792E27",
  },
  {
    colour: "sandybrown",
    description: "Medium Sand Brown",
    hex: "#EBAC4A, #F6A763, #FCB76C, #e9d443",
  },
  { colour: "seagreen", description: "Deep Green-Blue", hex: "#03ad50" },
  { colour: "sienna", description: "Burnt Orange-Brown", hex: "#91484c" },
  {
    colour: "silver",
    description: "Shiny Light Gray",
    hex: "#CCB7C3, #D8C6AB",
  },
  {
    colour: "steelblue",
    description: "Grayish-Blue Steel",
    hex: "#3A7195, #3D7889, #3a7295",
  },
  { colour: "tan", description: "Warm Light Brown", hex: "#E19E9F" },
  {
    colour: "teal",
    description: "Dark Greenish-Blue",
    hex: "#00798B, #03698B, #085881",
  },
  { colour: "wheat", description: "Light Golden Tan", hex: "#E9CCAD" },
  {
    colour: "yellowgreen",
    description: "Bright Yellowish-Green",
    hex: "#7EB159, #8EBF14, #AAAE45",
  },
];
